### ISSUE TITLE
ERROR: LoadDatabase: Unable to open:"PHREEQC.DAT"

### ISSUE THREAD

**Issue by S-AM-I** [simulkade/JPhreeqc.jl#1]
I am using windows 10 and the latest version of JPhreeqc.jl, with all the necessary C++ libraries installed. I get an error when trying to use the function:

```julia
RM_LoadDatabase(id, "PHREEQC.DAT")
```

The terminal outputs:
```
ERROR: LoadDatabase: Unable to open:"PHREEQC.DAT".
Stopping.
ERROR: LoadDatabase: Unable to open:"PHREEQC.DAT".
Stopping.
ERROR: LoadDatabase: Unable to open:"PHREEQC.DAT".
Stopping.
ERROR: LoadDatabase: Unable to open:"PHREEQC.DAT".

ERROR: LoadDatabase: Unable to open:"PHREEQC.DAT".

ERROR: LoadDatabase: Unable to open:"PHREEQC.DAT".

ERROR: PhreeqcRM failed.
ERROR: PhreeqcRM::LoadDatabase
```
After this error is output to the terminal, vscode then shows an error:
![Untitled](https://user-images.githubusercontent.com/40266704/117966434-cd9c6600-b31b-11eb-9567-ffacaeafb8d0.png)

Any help troubleshooting this would be greatly appreciated!
Thanks

**Comment by simulkade** [comment]
Hi @SA8416 . Do you have PHREEQC.DAT in your current path? You can copy it from the database folder to where your script/current path is. Alternatively, you can give the absolute path to the file PHREEQC.DAT in your function call.
I'll have to look for a better solution for the standard databases. In my PhreeqcMatlab tool, I have defined a function that returns the path to the database folder. I will probably define a constant that points to the database folder.

**Comment by S-AM-I** [comment]
Yes I have the .dat file in my current path- I copied it to where my script is, similar to your setup in https://github.com/simulkade/peteng/tree/master/phreeqcsample
But both my script (and yours from the link above) return the same database error. I will have a look at your PhreeqcMatlab tool and see if I can copy the function there.
Thanks!

**Comment by simulkade** [comment]
Can you try the absolute path in RM_LoadDatabase function, @SA8416 ?

**Comment by S-AM-I** [comment]
Using the absolute path via:

```Julia
dir_name = join path(@__DIR__, "phreeqc.dat")
```
seems to have solved the problem!

Thank you very much!!
